import NavBar from "./navigation";
import { Montserrat } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Pagina de Prueba Next JS",
  description: "Generated by Next.js",
};

const Mont = Montserrat({ weight: ["300", "400", "500"], styles: ["italic", "normal"], subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={Mont.className}>
        <NavBar />
        <div className="pt-24 p-20">{children}</div>
      </body>
    </html>
  );
}
