import List from "./list";

export const metadata = {
  title: "Datos especificos",
  description: "Generated by Next.js",
};

function Consult() {
  return (
    <div>
      <h3 className="font-bold text-2xl">Lista de datos</h3>
      <List />
    </div>
  );
}

export default Consult;
